server:
  port: 9091

spring:
  application:
    name: TEST_DEPLOYMENT

  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: testuser
    password: testuser

  jpa:
    show-sql: true
sonar:
  login: 5e370d8a950718a116fc9d9c1a930964dcb7fe6e